# Generated by Django 4.2.2 on 2023-06-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="rec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute", models.CharField(max_length=255)),
                ("academic", models.CharField(max_length=255)),
                ("quota", models.CharField(max_length=2)),
                ("seattype", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("openingrank", models.IntegerField()),
                ("closingrank", models.IntegerField()),
                ("year", models.IntegerField()),
                ("round", models.IntegerField()),
            ],
        ),
    ]
